# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KMBRLYGL's Design Portfolio
email: klosenara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Digital stomping grounds of a visual designer, Kimberly Gail.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kmbrlygl.github.io" # the base hostname & protocol for your site
twitter_username: kmbrlygl
github_username: kmbrlygl
instagram_username: thingsmyhandscreate

#Project url
permalink: /work/:title/

# Build settings
markdown: kramdown
